(load (expand-file-name "src/bootstrap.el" user-emacs-directory))
(load (expand-file-name "src/common.el" user-emacs-directory))
(load (expand-file-name "src/themes.el" user-emacs-directory))
(load (expand-file-name "src/languages.el" user-emacs-directory))
(load (expand-file-name "src/vc.el" user-emacs-directory))
